# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

import datetime
import os
import sys

now = datetime.datetime.now()

# Add the repo root so sphinx can find all packages
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

# -- Project information -----------------------------------------------------

project = "honeybee-ph"
copyright = "{}, PH-Tools".format(str(now.year))
author = "PH-Tools"

# The full version, including alpha/beta/rc tags
release = "1.32.7"

# for example take major/minor
version = "1.32"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.imgmath",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinxcontrib.fulltoc",
    "sphinx.ext.napoleon",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

import sphinx_bootstrap_theme

html_theme = "bootstrap"
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

html_theme_options = {
    # For black navbar, do "navbar navbar-inverse"
    "navbar_class": "navbar navbar-inverse",
    # Fix navigation bar to top of page?
    "navbar_fixed_top": "true",
    "navbar_pagenav": True,
    "source_link_position": "nav",
    "bootswatch_theme": "united",
    "bootstrap_version": "3",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory.
html_static_path = ["_static"]

# Custom sidebar templates
html_sidebars = {"**": ["localtoc.html"]}


# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = "honeybeephdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}

latex_documents = [
    (
        master_doc,
        "honeybee-ph.tex",
        "honeybee-ph Documentation",
        "PH-Tools",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

man_pages = [(master_doc, "honeybee-ph", "honeybee-ph Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (
        master_doc,
        "honeybee-ph",
        "honeybee-ph Documentation",
        author,
        "honeybee-ph",
        "Passive House extension for honeybee.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

epub_title = project
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for autodoc extension --------------------------------------------
autodoc_default_options = {
    "inherited-members": True,
}

autodoc_member_order = "groupwise"


# -----------------------------------------------------------------------------


def setup(app):
    """Run custom code with access to the Sphinx application object."""
    app.add_css_file("custom.css")
